- name: qemu images directory 
  file: 
    state: directory 
    path: "{{ libvirt_dir }}/images"

- name: Check cloud image
  uri: 
    url: "{{ cloudimg_url }}"
    method: HEAD
  register: cloudimg_http_stat
  check_mode: no 

- name: Check local cloud image 
  stat: 
    path: "{{ libvirt_dir }}/images/{{ osversion }}-cloudimg-amd64.qcow2"
    get_checksum: no 
  register: cloudimg_local_stat 

- name: Download cloud image
  get_url:
    url: "{{ cloudimg_url }}"
    dest: "{{ libvirt_dir }}/images/{{ osversion }}-cloudimg-amd64.qcow2"
  when: not cloudimg_local_stat.stat.exists or 
        cloudimg_local_stat.stat.size != cloudimg_http_stat.content_length
  register: cloudimg_local_updated 
