- name: "Check if qemu image directory does exists"
  stat:
    path: "{{ libvirt_dir }}/images"
  register: imgdir
  tags:
    - imgdircheck

- fail:
    msg: "{{ libvirt_dir }}/images path doesn't exist"
  when: imgdir.stat.islnk is not defined
  tags:
    - imgdircheck

- name: qemu images directory 
  file: 
    state: directory 
    path: "{{ libvirt_dir }}/images"
  tags:
    - imgdircheck

- name: Test download url
  uri:
    url: "{{ cloudimg_url }}"
    method: HEAD
    return_content: no
    status_code: 200
    validate_certs: no
  register: check_imgurl
  run_once: true
  until: not check_imgurl.failed
  retries: 3
  delay: 3
  tags:
    - imgurlval

- name: "Check if qemu image directory does exists"
  stat:
    path: "{{ libvirt_dir }}/{{ cloudimg_file }}"
  register: imgdir
  tags:
    - imgfilecheck


- name: Download file with check
  get_url:
    url: "{{ cloudimg_url }}"
    dest: "{{ libvirt_dir }}/images/{{ cloudimg_file }}"
  when: imgfile.stat.islnk is not defined
  tags:
    - imgdownfile 
