---
- name: Set up Cloud Image
  include_tasks: cloud_img.yml

- name: Configure Virtual Machines
  include_tasks: vm.yml
  loop: "{{ virtual_machines }}"
  loop_control: 
    loop_var: vm

- name: Configure Volumes
  include_tasks: volumes.yml
  loop: "{{ virtual_machines | subelements('volumes', 'skip_missing=True') }}"
