---
- name: " {{ item.1.device }} :: Check if volume file exists"
  stat:
    path: " {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }}"
  register: volume_list
  tags:
    - volfilecheck
 
- name: " {{ item.1.device }} ::  Check if volume is attached on {{ item.0.name }}"
  shell: "virsh domblklist {{ item.0.name }} | grep vda | awk '{print $1}'"
  register: volume_attached
  tags:
    - vol_removedir

- name: " Create disk {{ libvirt_dir }}/images/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }}"
  shell: "qemu-img create -f {{ item.1.type }} {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }} {{ item.1.size }}"
  when: volfilecheck.stat.islnk is not defined
  tags:
    - volfilecreate

- name: " {{ item.1.device }} : Attach volume to {{ item.0.name }}"
  shell: "virsh attach-disk {{ item.0.name }} {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }} {{ item.1.device }} --live --config"
  when: vol.volume.device is not defined
