---

- name: " {{ item.1.device }} :: Check if volume file exists"
  stat:
    path: " {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }}"
  register: volumefile
  tags:
    - volfilecheck
 
- name: " {{ item.1.device }} ::  Check if volume is attached on {{ item.0.name }}"
  shell: "virsh domblklist {{ item.0.name }} | grep {{ item.1.device }} | awk '{print $1}'"
  register: volume_attached
  tags:
    - volattachcheck

- fail:
    msg: "{{ item.1.device }} :: Attached on {{ item.0.name }}"
  when: item.1.device == volume_attached.stdout


- name: " Create disk {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }}"
  shell: "qemu-img create -f {{ item.1.type }} {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }} {{ item.1.size }}"
  tags:
    - volfilecreate

- name: " {{ item.1.device }} : Attach volume to {{ item.0.name }}"
  shell: "virsh attach-disk {{ item.0.name }} {{ libvirt_dir }}/images/{{ item.0.name }}/{{ item.0.name }}-{{ item.1.device }}.{{ item.1.type }} {{ item.1.device }} --live --config"
  tags: 
    - volattachdisk

